### ISSUE TITLE
Bad gateway problem encountered when running update-servers

### ISSUE THREAD

**Issue by parhamsaremi** [nblockchain/geewallet#177]
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Some problem when connecting to 'https://free-autumn-wandering-thunder.quiknode.pro/d8ddd9232e5d79da0e0091e0c49adb8f5ccd9885/' ---> GWallet.Backend.Ether.UnhandledWebException: Backend not prepared for this WebException with Status[7] ---> System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at GWallet.Backend.Ether.Server.MaybeRethrowWebException(Exception ex) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\Ether\EtherServer.fs:line 121
   at GWallet.Backend.Ether.Server.ReworkException(Exception ex) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\Ether\EtherServer.fs:line 295
   at GWallet.Backend.Ether.Server.HandlePossibleEtherFailures@387-6.Invoke(Exception _arg2) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\Ether\EtherServer.fs:line 392
   at GWallet.Backend.Ether.Server.HandlePossibleEtherFailures@387-8.Invoke(Exception exn) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\Ether\EtherServer.fs:line 387
   at GWallet.Backend.Ether.Server.HandlePossibleEtherFailures@387-10.Invoke(Exception edi) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\Ether\EtherServer.fs:line 387
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt, FSharpFunc`2 catchFilter, ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   --- End of inner exception stack trace ---
   at GWallet.Backend.Ether.Server.Web3ServerToRetrievalFunc@406-2.Invoke(Exception _arg3) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\Ether\EtherServer.fs:line 415
   at GWallet.Backend.Ether.Server.Web3ServerToRetrievalFunc@406-5.Invoke(Exception exn) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\Ether\EtherServer.fs:line 406
      at GWallet.Backend.Ether.Server.Web3ServerToRetrievalFunc@406-7.Invoke(Exception edi) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\Ether\EtherServer.fs:line 406
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt, FSharpFunc`2 catchFilter, ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at GWallet.Backend.FSharpUtil.ReRaise(Exception ex) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\FSharpUtil.fs:line 206
   at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient.Run@136-8.Invoke(Exception _arg2) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\FaultTolerantParallelClient.fs:line 165
   at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient.Run@136-15.Invoke(Exception exn) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\FaultTolerantParallelClient.fs:line 136
   at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient.Run@136-17.Invoke(Exception edi) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\FaultTolerantParallelClient.fs:line 136
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt, FSharpFunc`2 catchFilter, ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient.clo@312-29.Invoke(ServerTask`2 _arg1) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\FaultTolerantParallelClient.fs:line 316
      at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at <StartupCode$GWallet-Backend>.$FaultTolerantParallelClient.WhenAny@118-7.Invoke(AsyncActivation`1 ctxt) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\FaultTolerantParallelClient.fs:line 118
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit()
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at GWallet.Backend.ServerManager.UpdateServersStats() in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Backend\ServerManager.fs:line 171
   at Program.UpdateServersStats() in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Frontend.Console\Program.fs:line 468
   at Program.main(String[] argv) in C:\Users\ASUS\source\repos\geewallet-github\src\GWallet.Frontend.Console\Program.fs:line 482
```

**Comment by knocte** [comment]
Fixed in https://github.com/nblockchain/geewallet/commit/f123fd9b747d033a80f3870ab8d37492d1d7ec09 , thanks for reporting.
