### ISSUE TITLE
IntegrationTests failed because of System.IO.IOException: The handshake failed due to an unexpected packet format.

### ISSUE THREAD

**Issue by parhamsaremi** [nblockchain/geewallet#184]
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 349
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 870
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 890
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1153
   at GWallet.Backend.ServerManager.UpdateServersStats() in D:\a\geewallet\geewallet\src\GWallet.Backend\ServerManager.fs:line 213
   at Program.UpdateServersStats() in D:\a\geewallet\geewallet\src\GWallet.Frontend.Console\Program.fs:line 509
   at Program.main(String[] argv) in D:\a\geewallet\geewallet\src\GWallet.Frontend.Console\Program.fs:line 530
```

**Comment by knocte** [comment]
You got this in CI, paste the URL of that CI run.

**Comment by parhamsaremi** [comment]
> You got this in CI, paste the URL of that CI run.

sure but won't CI runs expire after some time? that's why I didn't paste it.

**Comment by knocte** [comment]
> sure but won't CI runs expire after some time? that's why I didn't paste it.

But it's still valuable information until it expires. Also, pasting the CI link we know the crash happened in CI (as opposed to locally in your computer).

**Comment by parhamsaremi** [comment]
> > sure but won't CI runs expire after some time? that's why I didn't paste it.
> 
> But it's still valuable information until it expires. Also, pasting the CI link we know the crash happened in CI (as opposed to locally in your computer).

right 👍
