### ISSUE TITLE
Argument Exception in Integration-Test for windows

### ISSUE THREAD

**Issue by parhamsaremi** [nblockchain/geewallet#186]
Link of the GIthubCI: https://github.com/parhamsaremi/geewallet/actions/runs/3444631179/jobs/5747438329
```
Unhandled Exception: System.ArgumentException: The input sequence was empty.
Parameter name: source
   at Microsoft.FSharp.Collections.SeqModule.Head[T](IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 1364
   at <StartupCode$NOnion>.$TorGuard.Handshake@360-5.Invoke(CellNetInfo _arg34)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 416
   at <StartupCode$NOnion>.$TorGuard.ReceiveExpected@266-5.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@589.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 589
   at <StartupCode$NOnion>.$TorGuard.ReceiveInternal@237-13.Invoke(AsyncActivation`1 ctxt)
   at NOnion.Utility.StreamUtil.readUntilBufferIsFull@29-5.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 349
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 870
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 890
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1153
   at GWallet.Backend.ServerManager.UpdateServersStats() in D:\a\geewallet\geewallet\src\GWallet.Backend\ServerManager.fs:line 213
   at Program.UpdateServersStats() in D:\a\geewallet\geewallet\src\GWallet.Frontend.Console\Program.fs:line 509
   at Program.main(String[] argv) in D:\a\geewallet\geewallet\src\GWallet.Frontend.Console\Program.fs:line 530
```

**Comment by knocte** [comment]
This looks like a use of Seq.head in NOnion (instead of Seq.tryHead). Let's find it there.

**Comment by parhamsaremi** [comment]
> Seq.head

I just saw this. We have this in the TorGuard 🤔

**Comment by knocte** [comment]
Let's fix it then. This should have been caught by FSharpLint so we need to file an FSharpLint bug as well.

**Comment by parhamsaremi** [comment]
> Let's fix it then. This should have been caught by FSharpLint so we need to file an FSharpLint bug as well.

Sure, I'll create a PR now.

**Comment by knocte** [comment]
> Sure, I'll create a PR now.

Is it that easy to fix? I'm guessing you need to pick Afshin's brain to know what to do when there's no head.

**Comment by parhamsaremi** [comment]
> > Sure, I'll create a PR now.
> 
> Is it that easy to fix? I'm guessing you need to pick Afshin's brain to know what to do when there's no head.

Nope, I'm pretty much stcuk. I was playing with code and different solutions in the last hour.

**Comment by knocte** [comment]
ping afshin in telegram man, he might reply

**Comment by knocte** [comment]
ping afshin in tg man, he might reply
